name: test github action

on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_ENV: test-tag

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      # - name: Get Commit SHA
      #   shell: bash
      #   run: |
      #     echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # tags: ${{ env.GITHUB_ENV }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Random Number Generator
      #   uses: ./
      #   with:
      #     who-to-greet: 'Mona the Octocat'
      # - run: echo random-number "$RANDOM_NUMBER"
      #   shell: bash
      #   env:
      #     RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
